/* eip97_global_types.h
 *
 * EIP97 Global Control Driver Library Public Interface:
 * Common type Definitions
 *
 */

/* -------------------------------------------------------------------------- */
/*                                                                            */
/*   Module        : ddk197                                                   */
/*   Version       : 5.7.2                                                    */
/*   configuration : DDK-197-BSD                                              */
/*                                                                            */
/*   Date          : 2025-Nov-13                                              */
/*                                                                            */
/* Copyright (c) 2008-2025 by Rambus, Inc. and/or its subsidiaries.           */
/*                                                                            */
/* Redistribution and use in source and binary forms, with or without         */
/* modification, are permitted provided that the following conditions are     */
/* met:                                                                       */
/*                                                                            */
/* 1. Redistributions of source code must retain the above copyright          */
/* notice, this list of conditions and the following disclaimer.              */
/*                                                                            */
/* 2. Redistributions in binary form must reproduce the above copyright       */
/* notice, this list of conditions and the following disclaimer in the        */
/* documentation and/or other materials provided with the distribution.       */
/*                                                                            */
/* 3. Neither the name of the copyright holder nor the names of its           */
/* contributors may be used to endorse or promote products derived from       */
/* this software without specific prior written permission.                   */
/*                                                                            */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        */
/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR      */
/* A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT       */
/* HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,     */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT           */
/* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,      */
/* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY      */
/* THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT        */
/* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE      */
/* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.       */
/* -------------------------------------------------------------------------- */

#ifndef INCLUDE_GUARD_EIP97_GLOBAL_TYPES_H
#define INCLUDE_GUARD_EIP97_GLOBAL_TYPES_H

/*----------------------------------------------------------------------------
 * This module uses (requires) the following interface(s):
 */

// Driver Framework Basic Definitions API
#include "basic_defs.h"             // u32


/*----------------------------------------------------------------------------
 * Definitions and macros
 */

#define EIP97_GLOBAL_IOAREA_REQUIRED_SIZE       (2 * sizeof(void*))

/*----------------------------------------------------------------------------
 * eip97_global_error_t
 *
 * status (error) code type returned by these API functions
 * See each function "Return value" for details.
 *
 * EIP97_GLOBAL_NO_ERROR : successful completion of the call.
 * EIP97_GLOBAL_UNSUPPORTED_FEATURE_ERROR : not supported by the device.
 * EIP97_GLOBAL_ARGUMENT_ERROR :  invalid argument for a function parameter.
 * EIP97_GLOBAL_BUSY_RETRY_LATER : device is busy.
 * EIP97_GLOBAL_ILLEGAL_IN_STATE : illegal state transition
 */
typedef enum
{
    EIP97_GLOBAL_NO_ERROR = 0,
    EIP97_GLOBAL_UNSUPPORTED_FEATURE_ERROR,
    EIP97_GLOBAL_ARGUMENT_ERROR,
    EIP97_GLOBAL_BUSY_RETRY_LATER,
    EIP97_GLOBAL_ILLEGAL_IN_STATE
} eip97_global_error_t;

/*----------------------------------------------------------------------------
 * eip97_global_events_t
 *
 * Bit-mask for the events that can be generated by the EIP-97 HW modules:
 * DFE, DSE, EIP-96 PE
 */
typedef enum
{
    // Fatal error events
    EIP97_GLOBAL_DFE_DMA_ERROR_EVENT = BIT_0,
    EIP97_GLOBAL_DSE_DMA_ERROR_EVENT = BIT_1,
    EIP97_GLOBAL_PE_TIMEOUT_EVENT    = BIT_2
} eip97_global_events_t;

// Bit-mask for the events defined by eip97_global_events_t
typedef u32 eip97_global_event_status_t;

// place holder for device specific internal data
typedef struct
{
    u32 placeholder[EIP97_GLOBAL_IOAREA_REQUIRED_SIZE];
} eip97_global_io_area_t;


#endif /* INCLUDE_GUARD_EIP97_GLOBAL_TYPES_H */


/* end of file eip97_global_types.h */
