/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/* Copyright (c) 2020 Intel Corporation */

#ifndef _UAPI_LINUX_AXIADO_MCTP_H
#define _UAPI_LINUX_AXIADO_MCTP_H

#include <linux/ioctl.h>
#include <linux/types.h>

/*
 * axiado-mctp is a simple device driver exposing a read/write interface:
 *  +----------------------+
 *  | PCIe VDM Header      | 16 bytes (Big Endian)
 *  +----------------------+
 *  | MCTP Message Payload | 64/128/256/512 bytes (Big Endian)
 *  +----------------------+
 *
 * MCTP packet description can be found in DMTF DSP0238,
 * MCTP PCIe VDM Transport Specification.
 */

#define AXIADO_MCTP_PCIE_VDM_HDR_SIZE 16

/*
 * uevents generated by axiado-mctp driver
 */
#define AXIADO_MCTP_READY "PCIE_READY"

/*
 * maximum possible number of struct eid_info elements stored in list
 */
#define AXIADO_MCTP_EID_INFO_MAX 256

/*
 * MCTP operations
 * @AXIADO_MCTP_IOCTL_FILTER_EID: enable/disable filter incoming packets based
 * on Endpoint ID (BROKEN)
 * @AXIADO_MCTP_IOCTL_GET_BDF: read PCI bus/device/function of MCTP Controller
 * @AXIADO_MCTP_IOCTL_GET_MEDIUM_ID: read MCTP physical medium identifier
 * related to PCIe revision
 * @AXIADO_MCTP_IOCTL_GET_MTU: read max transmission unit (in bytes)
 * @AXIADO_MCTP_IOCTL_REGISTER_DEFAULT_HANDLER Register client as default
 * handler that receives all MCTP messages that were not dispatched to other
 * clients
 * @AXIADO_MCTP_IOCTL_REGISTER_TYPE_HANDLER Register client to receive all
 * messages of specified MCTP type or PCI vendor defined type
 * @AXIADO_MCTP_IOCTL_UNREGISTER_TYPE_HANDLER Unregister client as handler
 * for specified MCTP type or PCI vendor defined message type
 * @AXIADO_MCTP_GET_EID_INFO - deprecated, use AXIADO_MCTP_GET_EID_EXT instead
 * @AXIADO_MCTP_SET_EID_INFO - deprecated, use AXIADO_MCTP_SET_EID_EXT instead
 * @AXIADO_MCTP_GET_EID_EXT_INFO: read list of existing CPU EID and Domain ID
 * mappings and return count which is lesser of the two: requested count and existing count
 * @AXIADO_MCTP_SET_EID_EXT_INFO: write or overwrite already existing list of
 * CPU EID and Domain ID mappings
 * @AXIADO_MCTP_SET_OWN_EID: write/overwrite own EID information
 */

struct axiado_mctp_bdf {
	__u16 bdf;
};

struct axiado_mctp_medium_id {
	__u8 medium_id;
};

struct axiado_mctp_mtu {
	__u16 mtu;
};

struct axiado_mctp_filter_eid {
	__u8 eid;
	bool enable;
};

struct axiado_mctp_type_handler_ioctl {
	__u8 mctp_type;		/* MCTP message type as per DSP239*/
	/* Below params must be 0 if mctp_type is not Vendor Defined PCI */
	__u16 pci_vendor_id;	/* PCI Vendor ID */
	__u16 vendor_type;	/* Vendor specific type */
	__u16 vendor_type_mask; /* Mask applied to vendor type */
};

struct axiado_mctp_eid_info {
	__u16 bdf;
	__u8 eid;
} __attribute__((packed));

struct axiado_mctp_eid_ext_info {
	struct axiado_mctp_eid_info eid;
	__u8 domain_id;
} __attribute__((packed));

struct axiado_mctp_get_eid_info {
	__u64 ptr;
	__u16 count;
	__u8 start_eid;
} __attribute__((packed));

struct axiado_mctp_set_eid_info {
	__u64 ptr;
	__u16 count;
};

struct axiado_mctp_set_own_eid {
	__u8 eid;
};

#define AXIADO_MCTP_IOCTL_BASE	0x4d

#define AXIADO_MCTP_IOCTL_FILTER_EID \
	_IOW(AXIADO_MCTP_IOCTL_BASE, 0, struct axiado_mctp_filter_eid)
#define AXIADO_MCTP_IOCTL_GET_BDF \
	_IOR(AXIADO_MCTP_IOCTL_BASE, 1, struct axiado_mctp_bdf)
#define AXIADO_MCTP_IOCTL_GET_MEDIUM_ID \
	_IOR(AXIADO_MCTP_IOCTL_BASE, 2, struct axiado_mctp_medium_id)
#define AXIADO_MCTP_IOCTL_GET_MTU \
	_IOR(AXIADO_MCTP_IOCTL_BASE, 3, struct axiado_mctp_mtu)
#define AXIADO_MCTP_IOCTL_REGISTER_DEFAULT_HANDLER \
	_IO(AXIADO_MCTP_IOCTL_BASE, 4)
#define AXIADO_MCTP_IOCTL_REGISTER_TYPE_HANDLER \
	_IOW(AXIADO_MCTP_IOCTL_BASE, 6, struct axiado_mctp_type_handler_ioctl)
#define AXIADO_MCTP_IOCTL_UNREGISTER_TYPE_HANDLER \
	_IOW(AXIADO_MCTP_IOCTL_BASE, 7, struct axiado_mctp_type_handler_ioctl)
#define AXIADO_MCTP_IOCTL_GET_EID_INFO \
	_IOWR(AXIADO_MCTP_IOCTL_BASE, 8, struct axiado_mctp_get_eid_info) /* deprecated */
#define AXIADO_MCTP_IOCTL_SET_EID_INFO \
	_IOW(AXIADO_MCTP_IOCTL_BASE, 9, struct axiado_mctp_set_eid_info) /* deprecated */
#define AXIADO_MCTP_IOCTL_GET_EID_EXT_INFO \
	_IOW(AXIADO_MCTP_IOCTL_BASE, 10, struct axiado_mctp_get_eid_info)
#define AXIADO_MCTP_IOCTL_SET_EID_EXT_INFO \
	_IOW(AXIADO_MCTP_IOCTL_BASE, 11, struct axiado_mctp_set_eid_info)
#define AXIADO_MCTP_IOCTL_SET_OWN_EID \
	_IOW(AXIADO_MCTP_IOCTL_BASE, 12, struct axiado_mctp_set_own_eid)

#endif /* _UAPI_LINUX_AXIADO_MCTP_H */
