# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_AXIADO) += ax3000-evk.dtb
dtb-$(CONFIG_ARCH_AXIADO) += ax3000-scm3003-evk.dtb
dtb-$(CONFIG_ARCH_AXIADO) += ax3000-scm3002-evk.dtb
dtb-$(CONFIG_ARCH_AXIADO) += ax3080-evk.dtb
dtb-$(CONFIG_ARCH_AXIADO) += scm3080-mt-evk.dtb
