# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_AX3000) += ax3000-evk.dtb
dtb-$(CONFIG_ARCH_AX3000) += ax3000-scm3003-evk.dtb
dtb-$(CONFIG_ARCH_AX3000) += ax3000-scm3002-evk.dtb
dtb-$(CONFIG_ARCH_AX3000) += ax3080-evk.dtb
dtb-$(CONFIG_ARCH_AX3000) += scm3080-mt-evk.dtb
dtb-$(CONFIG_ARCH_AX3005) += ax3005-evk.dtb
dtb-$(CONFIG_ARCH_AX3005) += scm3005-mt-evk.dtb
