# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PCIE_PLDA_HOST) += pcie-plda-host.o
obj-$(CONFIG_PCIE_MICROCHIP_HOST) += pcie-microchip-host.o
obj-$(CONFIG_PCIE_STARFIVE_HOST) += pcie-starfive.o
obj-$(CONFIG_PCIE_AXIADO_END_POINT) += axiado_pciecfg.o pcie-axiado.o pcie-axiado-common.o
