# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I $(srctree)/drivers/spi/

obj-$(CONFIG_AXIADO_LTPI)		+= ltpi-axiado.o
obj-$(CONFIG_AXIADO_SGPIO)		+= sgpio-axiado.o
obj-$(CONFIG_AXIADO_ESPI)		+= axiado-espi.o


